matrix:
  include:
    - language: node_js
      os:
        - linux
      #- osx
      #- windows
      node_js:
        - 14
      before_script:
        - cd ts
      script:
        - yarn install
        - yarn test

    - language: rust
      os:
        - linux
#      rust:
#        - stable
      before_script:
        - cd rs
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
        - cargo build
        - cargo test
        - cargo test --no-default-features

notifications:
  email: false
