[package]
name = "swf-types-bin"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Type definitions for the SWF file format"
documentation = "https://github.com/open-flash/swf-types"
homepage = "https://github.com/open-flash/swf-types"
repository = "https://github.com/open-flash/swf-types"
readme = "./README.md"
keywords = ["ast", "swf"]
license = "MIT/Apache-2.0"
edition = "2021"

[[bin]]
name = "swf-types"
path = "src/main.rs"

[dependencies]
serde_json_v8 = "^0.1.1"
swf-types = { path = "../." }
